export const categories = [
  ["Chiave inglese", "Cacciavite", "Martello", "Pinze", "Trapano"], // Tutte le parole sono strumenti usati per lavori meccanici (nomi)
  ["Adorabile", "Affascinante", "Amorevole", "Carino", "Commovente"], // Tutte le parole descrivono qualità piacevoli o attraenti (aggettivi)
  ["Cuocere", "Infornare", "Grigliare", "Soffriggere", "Arrostire"], // Tutte le parole descrivono metodi di preparazione del cibo (verbi)
  ["Tigre", "Leone", "Giaguaro", "Leopardo", "Ghepardo"], // Tutte le parole sono tipi di grandi felini (nomi)
  ["Imprevedibile", "Incostante", "Volatile", "Capriccioso", "Incoerente"], // Tutte le parole descrivono una mancanza di prevedibilità (aggettivi)
  ["Pianoforte", "Violino", "Violoncello", "Chitarra", "Arpa"], // Tutte le parole sono tipi di strumenti a corda (nomi)
  ["Navigare", "Dirigere", "Guidare", "Sterzare", "Pilotare"], // Tutte le parole riguardano il controllo del movimento di qualcosa (verbi)
  ["Desolato", "Deserto", "Vuoto", "Solitario", "Abbandonato"], // Tutte le parole descrivono una mancanza di abitanti o attività (aggettivi)
  ["Medico", "Infermiere", "Chirurgo", "Paramedico", "Dottore"], // Tutte le parole sono tipi di professionisti medici (nomi)
  ["Luminoso", "Splendente", "Radiante", "Raggiante", "Brillante"], // Tutte le parole descrivono luce intensa o luminosità (aggettivi)
  ["Tablet", "Laptop", "Smartphone", "Computer", "E-reader"], // Tutte le parole descrivono dispositivi elettronici (nomi)
  ["Eseguire", "Recitare", "Realizzare", "Consegnare", "Presentare"], // Tutte le parole riguardano il compiere azioni o compiti (verbi)
  ["Ardente", "Appassionato", "Fervente", "Zelante"], // Tutte le parole descrivono forti sentimenti o entusiasmo (aggettivi)
  ["Architetto", "Costruttore", "Ingegnere", "Disegnatore", "Progettista"], // Tutte le parole sono professionisti coinvolti in costruzione o design (nomi)
  ["Turbolento", "Tempestoso", "Agitato", "Mosso", "Instabile"], // Tutte le parole descrivono condizioni turbolente o instabili (aggettivi)
  ["Dibattere", "Discutere", "Argomentare", "Deliberare", "Negoziare"], // Tutte le parole coinvolgono lo scambio di idee o opinioni (verbi)
  ["Sereno", "Calmo", "Tranquillo", "Pacifico", "Quieto"], // Tutte le parole descrivono uno stato di calma (aggettivi)
  ["Tastiera", "Mouse", "Monitor", "Stampante", "Scanner"], // Tutte le parole sono dispositivi periferici per computer (nomi)
  ["Infastidire", "Irritare", "Disturbare", "Incomodare", "Agitare"], // Tutte le parole descrivono causare disagio o fastidio (verbi)
  ["Brillante", "Genio", "Intelligente", "Sveglio", "Saggio"], // Tutte le parole descrivono alti livelli di intelletto o abilità (aggettivi)
  ["Bicicletta", "Monopattino", "Skateboard", "Pattini a rotelle", "Segway"], // Tutte le parole sono tipi di dispositivi di trasporto personale (nomi)
  ["Resistere", "Sopportare", "Sopravvivere", "Persistere", "Superare"], // Tutte le parole riguardano il resistere o superare sfide (verbi)
  ["Misterioso", "Enigmatico", "Criptico", "Sconcertante", "Intrigante"], // Tutte le parole descrivono qualcosa di difficile da capire (aggettivi)
  ["Giacca", "Cappotto", "Maglione", "Gilet", "Blazer"], // Tutte le parole sono tipi di indumenti esterni (nomi)
  ["Urlare", "Gridare", "Stridere", "Ruggire", "Ulatare"], // Tutte le parole descrivono espressioni vocali rumorose (verbi)
  ["Antico", "Storico", "Vecchio", "Antiquato", "Eterno"], // Tutte le parole descrivono qualcosa con una lunga storia (aggettivi)
  ["Escursionismo", "Campeggio", "Pesca", "Ciclismo", "Arrampicata"], // Tutte le parole descrivono attività ricreative all'aperto (nomi)
  ["Scolpire", "Intagliare", "Cesellare", "Modellare"], // Tutte le parole riguardano la creazione di forme (verbi)
  ["Caldo", "Accogliente", "Confortevole", "Riscaldato", "Morbido"], // Tutte le parole descrivono un piacevole livello di calore (aggettivi)
  ["Prosperare", "Fiorire", "Avere successo", "Crescere"], // Tutte le parole riguardano sviluppo o progresso di successo (verbi)
  ["Noioso", "Smussato", "Stanco", "Piatto", "Poco eccitante"], // Tutte le parole descrivono una mancanza di acutezza o interesse (aggettivi)
  ["Quaderno", "Diario", "Blocco", "Agenda", "Taccuino"], // Tutte le parole sono tipi di superfici scritte rilegate (nomi)
  ["Energetico", "Dinamico", "Vivace", "Attivo"], // Tutte le parole descrivono alti livelli di energia o attività (aggettivi)
  ["Giungla", "Foresta", "Foresta pluviale", "Bosco", "Macchia"], // Tutte le parole sono tipi di ambienti boscosi densi (nomi)
  ["Elegante", "Lucidato", "Raffinato", "Liscio"], // Tutte le parole descrivono qualcosa con un aspetto raffinato o attraente (aggettivi)
  ["Sistema", "Rete", "Struttura", "Modello", "Schema"], // Tutte le parole descrivono insiemi organizzati o disposizioni (nomi)
  ["Opulento", "Lussuoso", "Sontuoso", "Straordinario", "Ricco"], // Tutte le parole descrivono alti livelli di lusso o ricchezza (aggettivi)
  ["Conferenza", "Seminario", "Workshop", "Simposio", "Vertice"], // Tutte le parole sono tipi di riunioni o incontri professionali (nomi)
  ["Schizzare", "Disegnare", "Delineare", "Illustrare", "Progettare"], // Tutte le parole riguardano la creazione di rappresentazioni visive (verbi)
  ["Curioso", "Inquisitivo", "Desideroso", "Interrogativo", "Interessato"], // Tutte le parole descrivono un desiderio di conoscenza o informazioni (aggettivi)
  ["Tavolozza", "Tela", "Cavalletto", "Pennello", "Pigmento"], // Tutte le parole sono strumenti o materiali usati nella pittura (nomi)
  ["Accelerare", "Velocizzare", "Incrementare", "Affrettare", "Sbrigare"], // Tutte le parole riguardano l'aumento di velocità o ritmo (verbi)
  ["Delicato", "Fragile", "Fragilissimo", "Tenero", "Debole"], // Tutte le parole descrivono qualcosa che è facilmente danneggiabile o rompibile (aggettivi)
  ["Calcolare", "Computare", "Misurare", "Stimare"], // Tutte le parole riguardano la determinazione di quantità o valori (verbi)
  ["Cuscino", "Coperta", "Piumone", "Lenzuolo", "Trapunta"], // Tutte le parole sono oggetti usati per la biancheria da letto o il sonno (nomi)
  ["Ispirare", "Motivare", "Incoraggiare", "Stimolare", "Influenzare"], // Tutte le parole riguardano la stimolazione di azioni o emozioni (verbi)
  ["Tappeto", "Stuoia", "Zerbino", "Passatoia", "Arazzo"], // Tutte le parole descrivono tipi di coperture per pavimenti (nomi)
  ["Analizzare", "Esaminare", "Scrutare", "Investigare", "Valutare"], // Tutte le parole riguardano lo studio approfondito di qualcosa (verbi)
  ["Criminale", "Delinquente", "Sospetto", "Autore di reato", "Trasgressore"], // Tutte le parole descrivono individui coinvolti in attività illegali (nomi)
  ["Ostacolo", "Barriera", "Impedimento", "Sfida", "Intralcio"], // Tutte le parole descrivono cose che ostacolano il progresso (nomi)
  ["Museo", "Galleria", "Mostra", "Esposizione", "Collezione"], // Tutte le parole sono relative a luoghi o eventi per esporre arte o manufatti (nomi)
  // TODO: Go through the rest of the categories and eliminate overlaps
  //
  // ["Empower", "Enable", "Authorize", "Facilitate", "Equip"], // All words relate to giving power or resources (verbs)
  // ["Opera", "Symphony", "Sonata", "Concerto", "Rhapsody"], // All words are types of classical music compositions (nouns)
  // ["Champion", "Victim", "Winner", "Contender", "Participant"], // All words describe roles in a competition or contest (nouns)
  // ["Excite", "Thrill", "Arouse", "Stimulate", "Energize"], // All words relate to causing strong feelings or reactions (verbs)
  // ["Grand", "Majestic", "Splendid", "Regal", "Impressive"], // All words describe something with grandeur or magnificence (adjectives)
  // ["Scientist", "Biologist", "Chemist", "Physicist", "Researcher"], // All words describe professionals in scientific fields (nouns)
  // ["Resolve", "Decide", "Determine", "Conclude", "Choose"], // All words relate to making decisions or finding solutions (verbs)
  // ["Sparse", "Scattered", "Thin", "Few", "Isolated"], // All words describe something with few elements or occurrences (adjectives)
  // ["Instrument", "Tool", "Device", "Apparatus", "Gadget"], // All words describe objects used for specific purposes (nouns)
  // ["Collaborate", "Cooperate", "Contribute", "Partner", "Assist"], // All words relate to working together or helping (verbs)
  // ["Photograph", "Snapshot", "Picture", "Image", "Portrait"], // All words describe types of visual representations captured by cameras (nouns)
  // ["Spacious", "Vast", "Expansive", "Wide", "Broad"], // All words describe large or open areas (adjectives)
  // ["Bacteria", "Virus", "Fungi", "Protozoa", "Microbe"], // All words describe microorganisms (nouns)
  // ["Vibrant", "Colorful", "Vivid"], // All words describe strong and lively colors or light (adjectives)
  // ["Puzzle", "Riddle", "Conundrum", "Enigma", "Brainteaser"], // All words describe problems requiring thought to solve (nouns)
  // ["Optimize", "Enhance", "Refine", "Improve", "Upgrade"], // All words relate to making something better (verbs)
  // ["Rustic", "Quaint", "Countryside", "Old-fashioned"], // All words describe traditional or rural qualities (adjectives)
  // ["Gadget", "Device", "Apparatus", "Instrument", "Tool"], // All words are types of objects used for specific functions (nouns)
  // ["Communicate", "Transmit", "Relay", "Convey", "Disseminate"], // All words relate to sending information or messages (verbs)
  // ["Unusual", "Unique", "Rare", "Strange", "Exceptional"], // All words describe something out of the ordinary (adjectives)
  // ["Chair", "Table", "Sofa", "Couch", "Bench"], // All words are types of furniture (nouns)
  // ["Transform", "Convert", "Change", "Alter", "Modify"], // All words relate to making changes to something (verbs)
  // ["Book", "Magazine", "Journal", "Newspaper", "Article"], // All words are types of written publications (nouns)
  // ["Imposing", "Grand", "Majestic", "Dignified", "Statuesque"], // All words describe something with a commanding presence (adjectives)
  // ["Artist", "Musician", "Painter", "Sculptor", "Writer"], // All words describe people involved in creative work (nouns)
  // ["Energize", "Stimulate", "Invigorate", "Excite", "Revitalize"], // All words relate to increasing energy or enthusiasm (verbs)
  // ["Clarify", "Explain", "Elucidate", "Illuminate", "Define"], // All words relate to making something clear or understandable (verbs)
  // ["Durable", "Sturdy", "Robust", "Resilient", "Tough"], // All words describe something that is strong and long-lasting (adjectives)
  // ["Camera", "Tripod", "Lens", "Flash", "Viewfinder"], // All words are parts or accessories for photography (nouns)
  // ["Modify", "Alter", "Adjust", "Change", "Revise"], // All words relate to making changes to something (verbs)
  // ["Beverage", "Drink", "Juice", "Smoothie", "Cocktail"], // All words are types of drinks (nouns)
  // ["Bureau", "Desk", "Table", "Workstation", "Counter"], // All words are types of surfaces used for work (nouns)
  // ["Exciting", "Thrilling", "Stimulating", "Invigorating", "Electrifying"], // All words describe something that causes strong feelings (adjectives)
  // ["Event", "Occasion", "Celebration", "Gathering", "Function"], // All words describe types of social or formal activities (nouns)
  // ["Vast", "Expansive", "Wide", "Immense", "Broad"], // All words describe something with a large area or scope (adjectives)
  // ["Candle", "Lamp", "Lantern", "Torch", "Lightbulb"], // All words are sources of artificial light (nouns)
  // ["Simplify", "Streamline", "Clarify", "Ease", "Facilitate"], // All words relate to making something less complicated (verbs)
  // ["Bold", "Brave", "Daring", "Courageous", "Audacious"], // All words describe a willingness to face risks (adjectives)
  // ["Library", "Archive", "Collection", "Depot", "Repository"], // All words are places or collections for storing information (nouns)
  // ["Reorganize", "Restructure", "Sort", "Arrange", "Order"], // All words relate to arranging or organizing things (verbs)
  // ["Nurturing", "Caring", "Supportive", "Protective", "Empathetic"], // All words describe providing emotional or physical support (adjectives)
  // ["Instrument", "Tool", "Device", "Apparatus", "Gadget"], // All words describe objects used for specific purposes (nouns)
  // ["Edit", "Revise", "Modify", "Update", "Correct"], // All words relate to making changes or improvements (verbs)
  // ["Fiction", "Novel", "Short story", "Tale", "Fantasy"], // All words describe genres or types of imaginative writing (nouns)
  // ["Collaborate", "Work", "Join", "Partner", "Unite"], // All words relate to working together with others (verbs)
  // ["Complex", "Intricate", "Detailed", "Elaborate", "Complicated"], // All words describe something with many parts or details (adjectives)
  // ["Document", "Record", "File", "Report", "Memo"], // All words are types of written or recorded information (nouns)
  // ["Resilient", "Flexible", "Adaptable", "Strong", "Tough"], // All words describe the ability to withstand or adapt (adjectives)
  // ["Detector", "Sensor", "Gage", "Indicator"], // All words are devices used to measure or detect changes (nouns)
  // ["Unique", "Uncommon", "Rare", "Distinctive", "Exceptional"], // All words describe something that stands out from the norm (adjectives)
  // ["Survey", "Examination", "Analysis", "Assessment", "Review"], // All words relate to evaluating or investigating something (nouns)
  // ["Elaborate", "Develop", "Expand", "Detail", "Clarify"], // All words relate to providing more information or detail (verbs)
  // ["Spacious", "Vast", "Wide", "Roomy", "Expansive"], // All words describe having a lot of space (adjectives)
  // ["Mirror", "Lens", "Prism", "Glass", "Optics"], // All words relate to objects used in optical processes (nouns)
  // ["Dismantle", "Disassemble", "Take apart", "Deconstruct", "Unpack"], // All words relate to separating something into parts (verbs)
  // ["Gadget", "Device", "Appliance", "Tool", "Instrument"], // All words describe objects designed for specific functions (nouns)
  // ["Combine", "Merge", "Integrate", "Unite", "Blend"], // All words relate to bringing things together (verbs)
  // ["Creative", "Innovative", "Imaginative", "Inventive", "Original"], // All words describe high levels of originality and creativity (adjectives)
  // ["Ruler", "Compass", "Protractor", "Divider", "Caliper"], // All words are tools used for measurement and drawing (nouns)
  // ["Vehicle", "Automobile", "Car", "Truck", "Motorcycle"], // All words describe modes of personal transportation (nouns)
  // ["Organize", "Arrange", "Sort", "Categorize", "Systematize"], // All words relate to structuring or ordering items (verbs)
  // ["Pyramid", "Sphere", "Cube", "Cone", "Cylinder"], // All words are geometric shapes (nouns)
  // ["Familiar", "Recognizable", "Known", "Accustomed", "Unusual"], // All words describe the degree to which something is known or typical (adjectives)
  // ["Painter", "Sculptor", "Artist", "Illustrator", "Photographer"], // All words describe individuals involved in creative visual arts (nouns)
  // ["Compile", "Gather", "Collect", "Assemble", "Accumulate"], // All words relate to bringing together items or information (verbs)
  // ["Aquarium", "Terrarium", "Vivarium", "Tank", "Enclosure"], // All words are types of containers for living organisms (nouns)
  // ["Facilitate", "Aid", "Assist", "Support", "Help"], // All words relate to providing assistance or making processes easier (verbs)
  // ["Ecosystem", "Biome", "Habitat", "Environment", "Niche"], // All words describe ecological systems or environments (nouns)
  // ["Neglect", "Overlook", "Disregard", "Ignore", "Dismiss"], // All words relate to failing to pay attention to something (verbs)
  // ["Clothing", "Apparel", "Garments", "Attire", "Outfit"], // All words describe items worn on the body (nouns)
  // ["Organize", "Arrange", "Coordinate", "Sort", "Order"], // All words relate to structuring or systematizing things (verbs)
  // ["Sophisticated", "Complex", "Intricate", "Advanced", "Elaborate"], // All words describe something with many parts or details (adjectives)
  // ["Transmit", "Send", "Relay", "Dispatch", "Broadcast"], // All words relate to sending information or signals (verbs)
  // ["Crucible", "Beaker", "Flask", "Test tube", "Centrifuge"], // All words are laboratory equipment (nouns)
  // ["Toolbox", "Bag", "Case", "Container", "Kit"], // All words are items used for carrying or organizing tools (nouns)
  // ["Engage", "Participate", "Join", "Involve", "Take part"], // All words relate to taking an active role in something (verbs)
  // ["Unusual", "Strange", "Rare", "Odd", "Uncommon"], // All words describe something not typical or frequent (adjectives)
  // ["Dining", "Breakfast", "Lunch", "Dinner", "Supper"], // All words are types of meals (nouns)
  // ["Cell", "Organism", "Bacterium", "Tissue", "Organ"], // All words are biological units or structures (nouns)
  // ["Edit", "Revise", "Modify", "Update", "Correct"], // All words relate to making changes or improvements (verbs)
  // ["Sculpture", "Painting", "Drawing", "Print", "Mosaic"], // All words describe forms of visual art (nouns)
  // ["Facilitate", "Assist", "Help", "Enable", "Support"], // All words relate to providing aid or making processes easier (verbs)
  // ["Eloquent", "Articulate", "Fluent", "Persuasive", "Expressive"], // All words describe effective verbal communication (adjectives)
  // ["Island", "Peninsula", "Coast", "Bay", "Archipelago"], // All words describe geographical landforms related to water (nouns)
  // ["Device", "Gadget", "Tool", "Instrument", "Appliance"], // All words describe objects used for specific functions (nouns)
  // ["Magnify", "Enlarge", "Expand", "Increase", "Amplify"], // All words relate to making something larger or more intense (verbs)
  // ["Gym", "Fitness center", "Health club", "Exercise room", "Workout space"], // All words describe places for physical exercise (nouns)
  // ["Energize", "Revitalize", "Invigorate", "Stimulate", "Excite"], // All words relate to increasing energy or enthusiasm (verbs)
  // ["Simple", "Easy", "Straightforward", "Basic", "Clear"], // All words describe something uncomplicated or easy to understand (adjectives)
  // ["Reflect", "Mirror", "Echo", "Resonate", "Reverberate"], // All words relate to the bouncing back of sound or light (verbs)
  // ["Excited", "Thrilled", "Energized", "Aroused", "Stimulated"], // All words describe a state of heightened excitement (adjectives)
  // ["Harbor", "Port", "Dock", "Marina", "Quay"], // All words describe places for docking ships or boats (nouns)
  // ["Convey", "Express", "Transmit", "Communicate", "Articulate"], // All words relate to sending or sharing information (verbs)
  // ["Data", "Information", "Statistics", "Facts", "Figures"], // All words are types of quantitative or factual content (nouns)
  // ["Calibrate", "Adjust", "Set", "Fine-tune", "Modify"], // All words relate to making precise changes (verbs)
  // ["Room", "Space", "Area", "Zone", "Section"], // All words describe parts of a larger space or area (nouns)
  // ["Develop", "Create", "Form", "Build", "Construct"], // All words relate to making or putting something together (verbs)
  // ["Workstation", "Desk", "Table", "Counter", "Workspace"], // All words are surfaces or areas used for work (nouns)
  // ["Excitement", "Thrill", "Elation", "Euphoria", "Enthusiasm"], // All words describe high levels of emotional arousal (nouns)
  // ["Conclude", "Complete", "Finish", "Close", "Wrap up"], // All words relate to bringing something to an end (verbs)
  // ["Inventive", "Creative", "Innovative", "Original", "Imaginative"], // All words describe high levels of originality and creativity (adjectives)
  // ["Intense", "Strong", "Powerful", "Vivid", "Deep"], // All words describe something with a high degree of force or impact (adjectives)
  // ["Idea", "Concept", "Notion", "Thought", "Theory"], // All words describe abstract mental representations (nouns)
  // ["Adapt", "Adjust", "Modify", "Change", "Revise"], // All words relate to making alterations (verbs)
  // ["Journey", "Trip", "Excursion", "Voyage", "Adventure"], // All words describe types of travel or exploration (nouns)
  // ["Transform", "Change", "Alter", "Modify", "Reform"], // All words relate to making changes to something (verbs)
  // ["Innovative", "Cutting-edge", "Advanced", "Novel", "Pioneering"], // All words describe high levels of newness or advancement (adjectives)
  // ["Capture", "Record", "Photograph", "Snap", "Film"], // All words relate to taking visual representations (verbs)
  // ["Grand", "Majestic", "Impressive", "Regal", "Stately"], // All words describe something with a grand appearance (adjectives)
  // ["Collaborate", "Cooperate", "Team up", "Join forces", "Work together"], // All words relate to working jointly with others (verbs)
  // ["Sturdy", "Durable", "Robust", "Resilient", "Tough"], // All words describe something that is strong and able to withstand wear (adjectives)
  // ["Spectacular", "Amazing", "Incredible", "Stunning", "Astonishing"], // All words describe something that is impressive or awe-inspiring (adjectives)
  // ["Instrument", "Device", "Tool", "Apparatus", "Gadget"], // All words are types of objects used for specific functions (nouns)
  // ["Simplify", "Clarify", "Streamline", "Facilitate", "Ease"], // All words relate to making something easier or clearer (verbs)
  // ["Healthy", "Fit", "Well", "Strong", "Robust"], // All words describe a state of good physical condition (adjectives)
  // ["Creative", "Innovative", "Imaginative", "Inventive", "Original"], // All words describe high levels of originality and creativity (adjectives)
  // ["Bureau", "Desk", "Counter", "Workstation", "Table"], // All words are types of surfaces used for work or organization (nouns)
  // ["Grand", "Majestic", "Impressive", "Regal", "Stately"], // All words describe something with grandeur or magnificence (adjectives)
  // ["Transform", "Change", "Alter", "Modify", "Revise"], // All words relate to making changes to something (verbs)
  // ["Decorate", "Embellish", "Adorn", "Ornament", "Enhance"], // All words describe adding beauty or detail (verbs)
  // ["Unique", "Distinctive", "Exceptional", "Uncommon", "Rare"], // All words describe something that stands out or is not ordinary (adjectives)
  // ["Exciting", "Thrilling", "Stimulating", "Invigorating", "Electrifying"], // All words describe something that causes strong feelings (adjectives)
  // ["Document", "Record", "File", "Report", "Log"], // All words are types of written or recorded information (nouns)
  // ["Transform", "Change", "Alter", "Modify", "Adjust"], // All words relate to making changes to something (verbs)
  // ["Creative", "Innovative", "Imaginative", "Original", "Inventive"], // All words describe high levels of originality and creativity (adjectives)
  // ["Adjust", "Modify", "Alter", "Change", "Revise"], // All words relate to making changes or improvements (verbs)
  // ["Grand", "Majestic", "Imposing", "Stately", "Regal"], // All words describe something with a grand or impressive appearance (adjectives)
  // ["Precise", "Exact", "Accurate", "Detailed", "Specific"], // All words describe a high level of correctness or exactness (adjectives)
  // ["Illuminate", "Light", "Brighten", "Shine", "Radiate"], // All words relate to providing light or making something brighter (verbs)
  // ["Precise", "Accurate", "Exact", "Detailed", "Meticulous"], // All words describe high levels of correctness and attention to detail (adjectives)
  // ["Concept", "Idea", "Notion", "Theory", "Belief"], // All words describe abstract mental representations or thoughts (nouns)
  // ["Concept", "Idea", "Theory", "Notion", "Belief"], // All words describe abstract mental representations or thoughts (nouns)
  // ["Unique", "Distinctive", "Exceptional", "Unusual", "Uncommon"], // All words describe something that is out of the ordinary or special (adjectives)
  // ["Transform", "Change", "Alter", "Modify", "Adjust"], // All words relate to making changes to something (verbs)
  // ["Journey", "Expedition", "Adventure", "Trip", "Voyage"], // All words describe types of travel or exploration (nouns)
  // ["Innovative", "Creative", "Imaginative", "Inventive", "Original"], // All words describe high levels of originality and creativity (adjectives)
  // ["Complicated", "Complex", "Intricate", "Detailed", "Elaborate"], // All words describe something with many parts or details (adjectives)
  // ["Collaborate", "Partner", "Join", "Cooperate", "Work together"], // All words relate to working together with others (verbs)
  // ["Traditional", "Classic", "Conventional", "Timeless", "Heritage"], // All words describe something that has a long history or established form (adjectives)
  // ["Instrument", "Device", "Tool", "Apparatus", "Gadget"], // All words describe objects designed for specific functions (nouns)
  // ["Visualize", "Imagine", "Envision", "Picture", "Conceptualize"], // All words relate to creating mental images or ideas (verbs)
  // ["Innovative", "Original", "Creative", "Inventive", "Groundbreaking"], // All words describe high levels of newness or advancement (adjectives)
  // ["Timeless", "Classic", "Enduring", "Evergreen", "Traditional"], // All words describe something that remains relevant or stylish over time (adjectives)
  // ["Interactive", "Engaging", "Participatory", "Immersive", "Involving"], // All words describe something that actively involves the participant (adjectives)
  // ["Innovative", "Creative", "Original", "Cutting-edge", "Novel"], // All words describe high levels of newness or advancement (adjectives)
  // ["Sculpture", "Painting", "Drawing", "Print", "Collage"], // All words describe forms of visual art (nouns)
  // ["Conceptualize", "Visualize", "Envision", "Imagine"], // All words relate to forming or creating mental images or ideas (verbs)
  // ["Enlighten", "Educate", "Illuminate", "Inform", "Instruct"], // All words relate to providing knowledge or clarity (verbs)
  // ["Splendid", "Magnificent", "Grand", "Impressive"], // All words describe something that is impressive or awe-inspiring (adjectives)
  // ["Envision", "Imagine", "Visualize", "Picture", "Conceptualize"], // All words relate to creating mental images or ideas (verbs)
  // ["Pioneering", "Innovative", "Groundbreaking", "Trailblazing", "Avant-garde"], // All words describe high levels of newness or advancement (adjectives)
  // ["Sophisticated", "Complex", "Intricate", "Refined", "Advanced"], // All words describe something with a high level of detail or advancement (adjectives)
  // ["Streamline", "Simplify", "Optimize", "Facilitate", "Enhance"], // All words relate to making something more efficient or effective (verbs)
  // ["Captivating", "Enchanting", "Alluring", "Delightful"], // All words describe something that attracts or fascinates (adjectives)
  // ["Cutting-edge", "Innovative", "Pioneering", "Advanced", "State-of-the-art"], // All words describe high levels of newness or advancement (adjectives)
  // ["Artistic", "Creative", "Imaginative", "Inventive", "Original"], // All words describe high levels of creativity and artistic flair (adjectives)
  // ["Modern", "Contemporary", "Current", "Up-to-date", "Recent"], // All words describe something that is in line with present trends or times (adjectives)
  // ["Inventive", "Creative", "Innovative", "Original", "Imaginative"], // All words describe high levels of creativity and originality (adjectives)
  // ["Intricate", "Complex", "Detailed", "Elaborate", "Complicated"], // All words describe something with many parts or details (adjectives)
  // ["Collaborate", "Partner", "Join", "Work together", "Cooperate"], // All words relate to working together with others (verbs)
];
